version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  qcluster:
    build: .
    command: >
      sh -c "python manage.py migrate django_q &&
             python manage.py shedule &&
             python manage.py qcluster"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env